### ISSUE TITLE
Revit 2023 - Scripts don't run properly

### ISSUE THREAD

**Issue by ilyasab3** [johnpierson/Relay#11]
I have tried the latest release on Revit 2023. After pushing a script button it takes some time as if Dynamo is being loaded, but then no result appears (e.g. HelloWorld dialog box does not appear).
 I hope it is only some library dependencies and not a core change in Dynamo API way of running graphs.

**Comment by johnpierson** [comment]
Hmm, I had not built Relay for Revit 2023 until today. Give this version a try for me: https://github.com/johnpierson/Relay/releases/tag/v1.2.0

**Comment by ilyasab3** [comment]
Thank you for the update! It works perfectly for me.
