### ISSUE TITLE
UX improvement suggestions

### ISSUE THREAD

**Issue by chuncahk** [johnpierson/Relay#12]
This is a great add-in to solve my problem with Dynamo Player. It works as I expected.
However, I wonder is it possible to custom the path of the scripts folder instead of the default path?
It is because I normally store and edit my Dynamo scripts in cloud folder for backup and version control purpose.

Also, is it possible to auto load scripts collection instead of clicking Sync Graphs after every time Revit started.

Thank you so much so this add-in

**Comment by johnpierson** [comment]
Hi there @chunchk , I will look at options for remapping in the future. At this time, it was simplest to have that as a default location.

**Comment by johnpierson** [comment]
Closing this as it is related to #17, which has a few additional ideas.
