### ISSUE TITLE
Large Icons

### ISSUE THREAD

**Issue by MonkeyWarrior** [johnpierson/Relay#13]
The ability to choose between large/small icons as the button selection would be awesome! 

Maybe something like; if image_32 exists, large icon, if not small icon?

**Comment by chuncahk** [comment]
That would be nice~
but I think the logic should be altered a little to 
if image_16 exist, can be small icon
else , only large icon

**Comment by johnpierson** [comment]
> if image_16 exist, can be small icon
else , only large icon

Unfortunately, it cannot work this way as small icons can use the 32 image and large icons cannot use the 16. So we want to target the way @MonkeyWarrior mentioned.
