### ISSUE TITLE
Installing relay on revit 2023

### ISSUE THREAD

**Issue by ChrisDHME** [johnpierson/Relay#15]
I've followed the tutorial from 
https://www.notion.so/Relay-for-Revit-6732550b41d34bce8edc518c0d0e47b9
to install it on my revit 2023. 
However when starting revit, I get this error:
![image](https://github.com/johnpierson/Relay/assets/137053956/b138d8bd-6143-4e9d-bc0f-3eb1d1076c76)

I have tried the solution in:
https://github.com/johnpierson/Relay/issues/10
But that doesn't fix it either.

**Comment by chuncahk** [comment]
I also had this problem last week, so I change back to an older version and it works fine.
