### ISSUE TITLE
Problem: PotentialTabDirectories Setting 

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/Relay#20]
The problem is it will load include a folder language to create tab 
![image](https://github.com/johnpierson/Relay/assets/31106432/12fb3cea-628f-45d0-8b29-4c209921dfc7)

Issue : 
![Revit_44J3OyPxO6](https://github.com/johnpierson/Relay/assets/31106432/a5ad7d03-e95d-456c-ab68-fbe584d4955d)

**Comment by johnpierson** [comment]
This is part of the new debug it appears. Fixing that now.
