### ISSUE TITLE
Keep Runing the script

### ISSUE THREAD

**Issue by amirjalaliafshar** [johnpierson/Relay#3]
I have an issue, when I run the script through relay for Revit, after run the UI pop up again, I cancel it but it popup again some times it comes 4,5 times! after that if I touch elements which I placed them by script (Move,Delete) again the UI popup.!!
Does anyone have the same issue?

**Comment by johnpierson** [comment]
This release https://github.com/ParallaxTeam/Relay/releases/tag/v1.0.2a fixes that.
