### ISSUE TITLE
Revit External Tool Failure

### ISSUE THREAD

**Issue by gnye4598** [johnpierson/Relay#5]
Hi, I am brand new to Relay and am excited to try out the tool I think it will be extremely valuable for my firm. Upon downloading to my local drive folder I am receiving this popup saying that Revit cannot run the external application. Hope you can help, thanks.

Greg

![2021-05-19_17-22-13](https://user-images.githubusercontent.com/66739811/118886582-2a24f580-b8c7-11eb-88d8-b34f97978157.jpg)

**Comment by johnpierson** [comment]
Right-click on the DLL (after unzipping) and select "unblock".

How to unblock a DLL is demonstrated here: https://github.com/radumg/DynaWeb#still-cant-see-the-package-in-dynamo-

**Comment by gnye4598** [comment]
That did the job thank you!

**Comment by johnpierson** [comment]
Of course! Glad to help out. Have fun with the tool! 🙌

**Comment by gnye4598** [comment]
@johnpierson I'm noticing that since Relay must be located in our local C Drive folder, if others around the office are using the same folder, any time that I make changes or additions to the Relay Script folder it obviously only makes updates to my local folder. Is there a way Relay folders can be synced together for example if the folder can be located in a local network that everyone has access to?

**Comment by johnpierson** [comment]
Yeah unfortunately that is all we include in this tool at this time. This tool was meant more as a proof and free/open source tool for the community and we aren't really going to be adding any features like that to this version.

There _might_ be a way to modify the .addin manifest to point at a network location (relocate your whole relay folder). But that can get odd too.

My first choice would be to sync those .dyns locally somehow.

**Comment by johnpierson** [comment]
If I were still at a firm, I would really probably consider, https://www.orkestra.online/
because it does all of the management in the cloud for you. But I know that it is paid and sometimes that is a hard sell.

**Comment by gnye4598** [comment]
Good to know, I'll do some searching around and see if I can relay anything to you..no pun intended, sure seems to be an awesome tool though, makes using Dynamo for those unfamiliar so much less scary

**Comment by johnpierson** [comment]
Absolutely! Apologies for the minimal features right now. We were working on similar tools for other folks and though, "What the heck, we should make this part open source for people".

Maybe eventually we (Parallax) will have a (paid) scope that lets us add new features to this tool too. 🙂

**Comment by gnye4598** [comment]
Best of luck, excited about its potential!
